### ISSUE TITLE
lab4.1/catch a ball with best players.py

### ISSUE THREAD

**Issue by kolganovn** [python-practice-b02-006/emelianova#2]
Forgotten square of `r2_sup` in `check_click()`. Cannot catch the sun because of it :(
Also, it's not convenient to keep save data file in a repository. It can cause a merge conflict.

**Comment by EmelianovaTG** [comment]
Fixed the forgotten square. Also, increased the speed of the sun because you are not supposed to catch it :)
Deleted the data file from the repository.

**Comment by EmelianovaTG** [comment]
> Forgotten square of `r2_sup` in `check_click()`. Cannot catch the sun because of it :(
> Also, it's not convenient to keep save data file in a repository. It can cause a merge conflict.

Fixed the forgotten square. Also, increased the speed of the sun because you are not supposed to catch it :)
Deleted the data file from the repository.
